# Generated by Django 6.0.4 on 2026-04-10 16:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('specialties', models.CharField(blank=True, max_length=200, verbose_name='Spécialités')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingénieur',
                'verbose_name_plural': 'Ingénieurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nom du projet')),
                ('bon_commande_number', models.CharField(max_length=100, verbose_name='N° Bon de commande')),
                ('bon_commande_date', models.DateField(verbose_name='Date de réception du bon de commande')),
                ('gouvernorat', models.CharField(choices=[('ariana', 'Ariana'), ('beja', 'Béja'), ('ben_arous', 'Ben Arous'), ('bizerte', 'Bizerte'), ('gabes', 'Gabès'), ('gafsa', 'Gafsa'), ('jendouba', 'Jendouba'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('kebili', 'Kébili'), ('kef', 'Kef'), ('mahdia', 'Mahdia'), ('manouba', 'Manouba'), ('medenine', 'Médenine'), ('monastir', 'Monastir'), ('nabeul', 'Nabeul'), ('sfax', 'Sfax'), ('sidi_bouzid', 'Sidi Bouzid'), ('siliana', 'Siliana'), ('sousse', 'Sousse'), ('tataouine', 'Tataouine'), ('tozeur', 'Tozeur'), ('tunis', 'Tunis'), ('zaghouan', 'Zaghouan')], max_length=50, verbose_name='Gouvernorat')),
                ('maitre_ouvrage', models.CharField(max_length=200, verbose_name="Maître d'ouvrage")),
                ('maitre_ouvrage_type', models.CharField(choices=[('DRE', 'DRE'), ('CRE', 'CRE'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="Type maître d'ouvrage")),
                ('has_structure', models.BooleanField(default=False, verbose_name='Structure')),
                ('has_electricite', models.BooleanField(default=False, verbose_name='Électricité')),
                ('has_fluide', models.BooleanField(default=False, verbose_name='Fluide')),
                ('planned_visits', models.PositiveIntegerField(default=0, verbose_name='Visites prévues')),
                ('completed_visits', models.PositiveIntegerField(default=0, verbose_name='Visites réalisées')),
                ('dao_structure', models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='DAO Structure')),
                ('dao_electricite', models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='DAO Électricité')),
                ('dao_fluide', models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='DAO Fluide')),
                ('dao_completed_date', models.DateField(blank=True, null=True, verbose_name='Date de complétion DAO')),
                ('d0_done', models.BooleanField(default=False, verbose_name='D0 réalisé')),
                ('d0_date', models.DateField(blank=True, null=True, verbose_name='Date D0')),
                ('exe_structure', models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='EXE Structure')),
                ('exe_electricite', models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='EXE Électricité')),
                ('exe_fluide', models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='EXE Fluide')),
                ('exe_started_date', models.DateField(blank=True, null=True, verbose_name='Date début EXE')),
                ('d6_done', models.BooleanField(default=False, verbose_name='D6 réalisé')),
                ('d6_date', models.DateField(blank=True, null=True, verbose_name='Date D6')),
                ('rpro', models.BooleanField(default=False, verbose_name='RPRO (Réception provisoire)')),
                ('rpro_date', models.DateField(blank=True, null=True, verbose_name='Date RPRO')),
                ('rdef', models.BooleanField(default=False, verbose_name='RDEF (Réception définitive)')),
                ('rdef_date', models.DateField(blank=True, null=True, verbose_name='Date RDEF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('engineers', models.ManyToManyField(blank=True, to='projects.engineer', verbose_name='Ingénieurs')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('text', models.TextField(verbose_name='Observation')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveSmallIntegerField(choices=[(1, 'Facture N°1'), (2, 'Facture N°2'), (3, 'Facture N°3')], verbose_name='Numéro de facture')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name="Date d'établissement")),
                ('transmission_date', models.DateField(blank=True, null=True, verbose_name='Date de transmission')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['invoice_number'],
                'unique_together': {('project', 'invoice_number')},
            },
        ),
    ]
