# Generated by Django 6.0.4 on 2026-04-21 13:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name="Intitulé de l'expertise")),
                ('bon_commande_number', models.CharField(max_length=100, verbose_name='N° Bon de commande')),
                ('bon_commande_date', models.DateField(verbose_name='Date de réception du bon de commande')),
                ('gouvernorat', models.CharField(choices=[('ariana', 'Ariana'), ('beja', 'Béja'), ('ben_arous', 'Ben Arous'), ('bizerte', 'Bizerte'), ('gabes', 'Gabès'), ('gafsa', 'Gafsa'), ('jendouba', 'Jendouba'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('kebili', 'Kébili'), ('kef', 'Kef'), ('mahdia', 'Mahdia'), ('manouba', 'Manouba'), ('medenine', 'Médenine'), ('monastir', 'Monastir'), ('nabeul', 'Nabeul'), ('sfax', 'Sfax'), ('sidi_bouzid', 'Sidi Bouzid'), ('siliana', 'Siliana'), ('sousse', 'Sousse'), ('tataouine', 'Tataouine'), ('tozeur', 'Tozeur'), ('tunis', 'Tunis'), ('zaghouan', 'Zaghouan')], max_length=50, verbose_name='Gouvernorat')),
                ('maitre_ouvrage', models.CharField(max_length=200, verbose_name="Maître d'ouvrage")),
                ('maitre_ouvrage_type', models.CharField(choices=[('DRE', 'DRE'), ('CRE', 'CRE'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="Type maître d'ouvrage")),
                ('has_structure', models.BooleanField(default=False, verbose_name='Structure')),
                ('has_electricite', models.BooleanField(default=False, verbose_name='Électricité')),
                ('has_fluide', models.BooleanField(default=False, verbose_name='Fluide')),
                ('dossier_status', models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='Statut du dossier')),
                ('dossier_completed_date', models.DateField(blank=True, null=True, verbose_name='Date de complétion du dossier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expertises', to=settings.AUTH_USER_MODEL)),
                ('engineers', models.ManyToManyField(blank=True, to='projects.engineer', verbose_name='Ingénieurs')),
            ],
            options={
                'verbose_name': 'Expertise',
                'verbose_name_plural': 'Expertises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name="Date d'établissement")),
                ('transmission_date', models.DateField(blank=True, null=True, verbose_name='Date de transmission')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.expertise', verbose_name='Expertise')),
            ],
            options={
                'verbose_name': 'Facture Expertise',
                'verbose_name_plural': 'Factures Expertise',
            },
        ),
        migrations.CreateModel(
            name='ExpertiseObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('text', models.TextField(verbose_name='Observation')),
                ('is_auto', models.BooleanField(default=False, verbose_name='Automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='projects.expertise', verbose_name='Expertise')),
            ],
            options={
                'verbose_name': 'Observation Expertise',
                'verbose_name_plural': 'Observations Expertise',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
