# Generated by Django 6.0.4 on 2026-04-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_expertise_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='maitre_ouvrage_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='maitre_ouvrage_type',
        ),
    ]
