# Generated by Django 6.0.4 on 2026-04-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_maitre_ouvrage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='has_securite_incendie',
            field=models.BooleanField(default=False, verbose_name='Sécurité incendie'),
        ),
        migrations.AddField(
            model_name='project',
            name='dao_securite_incendie',
            field=models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='DAO Sécurité incendie'),
        ),
        migrations.AddField(
            model_name='project',
            name='exe_securite_incendie',
            field=models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='EXE Sécurité incendie'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_securite_incendie',
            field=models.BooleanField(default=False, verbose_name='Sécurité incendie'),
        ),
    ]
