# Generated by Django 6.0.4 on 2026-04-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_securite_incendie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='phone',
        ),
    ]
