# Generated by Django 6.0.4 on 2026-04-29 22:29

from django.db import migrations, models


def copy_dossier_status(apps, schema_editor):
    Expertise = apps.get_model('projects', 'Expertise')
    for e in Expertise.objects.all():
        old = e.dossier_status
        if e.has_structure:
            e.dossier_structure = old
        if e.has_electricite:
            e.dossier_electricite = old
        if e.has_fluide:
            e.dossier_fluide = old
        if e.has_securite_incendie:
            e.dossier_securite_incendie = old
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_engineer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='dossier_electricite',
            field=models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='Dossier Électricité'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_electricite_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='ELEC – Date décision'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_electricite_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='ELEC – Date réception'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_fluide',
            field=models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='Dossier Fluide'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_fluide_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='FL – Date décision'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_fluide_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='FL – Date réception'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_securite_incendie',
            field=models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='Dossier Sécurité incendie'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_securite_incendie_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='SI – Date décision'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_securite_incendie_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='SI – Date réception'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_structure',
            field=models.CharField(choices=[('non_prevu', 'Non prévu'), ('non_recu', 'Dossier non reçu'), ('non_approuve', 'Dossier non approuvé'), ('en_cours', 'En cours de vérification'), ('approuve', 'Approuvé')], default='non_prevu', max_length=20, verbose_name='Dossier Structure'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_structure_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='STR – Date décision'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='dossier_structure_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='STR – Date réception'),
        ),
        migrations.AddField(
            model_name='project',
            name='dao_electricite_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='DAO ELEC – Date décision'),
        ),
        migrations.AddField(
            model_name='project',
            name='dao_electricite_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='DAO ELEC – Date réception'),
        ),
        migrations.AddField(
            model_name='project',
            name='dao_fluide_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='DAO FL – Date décision'),
        ),
        migrations.AddField(
            model_name='project',
            name='dao_fluide_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='DAO FL – Date réception'),
        ),
        migrations.AddField(
            model_name='project',
            name='dao_securite_incendie_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='DAO SI – Date décision'),
        ),
        migrations.AddField(
            model_name='project',
            name='dao_securite_incendie_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='DAO SI – Date réception'),
        ),
        migrations.AddField(
            model_name='project',
            name='dao_structure_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='DAO STR – Date décision'),
        ),
        migrations.AddField(
            model_name='project',
            name='dao_structure_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='DAO STR – Date réception'),
        ),
        migrations.AddField(
            model_name='project',
            name='exe_electricite_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='EXE ELEC – Date décision'),
        ),
        migrations.AddField(
            model_name='project',
            name='exe_electricite_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='EXE ELEC – Date réception'),
        ),
        migrations.AddField(
            model_name='project',
            name='exe_fluide_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='EXE FL – Date décision'),
        ),
        migrations.AddField(
            model_name='project',
            name='exe_fluide_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='EXE FL – Date réception'),
        ),
        migrations.AddField(
            model_name='project',
            name='exe_securite_incendie_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='EXE SI – Date décision'),
        ),
        migrations.AddField(
            model_name='project',
            name='exe_securite_incendie_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='EXE SI – Date réception'),
        ),
        migrations.AddField(
            model_name='project',
            name='exe_structure_decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='EXE STR – Date décision'),
        ),
        migrations.AddField(
            model_name='project',
            name='exe_structure_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='EXE STR – Date réception'),
        ),
        migrations.RunPython(copy_dossier_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_status',
        ),
    ]
