# Generated by Django 6.0.4 on 2026-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_dossier_date_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_completed_date',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_electricite',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_electricite_decision_date',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_electricite_received_date',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_fluide',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_fluide_decision_date',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_fluide_received_date',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_securite_incendie',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_securite_incendie_decision_date',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_securite_incendie_received_date',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_structure',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_structure_decision_date',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='dossier_structure_received_date',
        ),
        migrations.AddField(
            model_name='expertise',
            name='rapport_status',
            field=models.CharField(choices=[('non_effectue', 'Non encore effectué'), ('en_cours', 'En cours')], default='non_effectue', max_length=20, verbose_name='Statut du rapport'),
        ),
    ]
