# Generated by Django 6.0.4 on 2026-08-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_expertise_rapport_final_project_vrd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
