# Generated by Django 6.0.4 on 2026-08-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_engineer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='rapport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date rapport'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='rapport_status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('cloturee', 'Clôturée')], default='en_cours', max_length=20, verbose_name='Statut expertise'),
        ),
    ]
