# Generated by Django 6.0.4 on 2026-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_expertise_rapport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='rapport_status',
            field=models.CharField(choices=[('non_effectue', 'Non encore effectué'), ('en_cours', 'En cours'), ('cloturee', 'Clôturée')], default='en_cours', max_length=20, verbose_name='Statut expertise'),
        ),
    ]
