databases:
  - name: maram-db
    databaseName: maram_db
    user: maram_user
    plan: free

services:
  - type: web
    name: maram
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "bash start.sh"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: maram-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@maram.tn
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@maram.tn
      - key: BOSS_EMAIL
        value: rajet.jerbi@gmail.com
      - key: LICENSED_TO
        value: MARAM
