# Generated by Django 6.0.4 on 2026-04-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('facture1_ready', 'Facture N°1 à établir'), ('facture1_j7', 'Rappel Facture N°1 – J-7'), ('facture1_j2', 'Rappel Facture N°1 – J-2'), ('facture1_overdue', 'Facture N°1 en retard'), ('facture2_ready', 'Facture N°2 à établir'), ('facture3_ready', 'Facture N°3 à établir'), ('d0_reminder', 'Rappel D0'), ('d6_reminder', 'Rappel D6')], max_length=30, unique=True, verbose_name='Type de notification')),
                ('channel', models.CharField(choices=[('app', 'Application'), ('email', 'Email'), ('both', 'Application + Email')], default='both', max_length=10, verbose_name='Canal par défaut')),
                ('send_to_project_engineers', models.BooleanField(default=True, verbose_name='Envoyer aux ingénieurs du projet')),
                ('send_to_billing_manager', models.BooleanField(default=True, verbose_name='Envoyer au responsable facturation')),
                ('send_to_admin', models.BooleanField(default=False, verbose_name="Envoyer à l'administrateur")),
                ('extra_emails', models.TextField(blank=True, help_text='Entrez une adresse email par ligne', verbose_name='Emails supplémentaires (un par ligne)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Paramètre de notification',
                'verbose_name_plural': 'Paramètres de notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('facture1_ready', 'Facture N°1 à établir'), ('facture1_j7', 'Rappel Facture N°1 – J-7'), ('facture1_j2', 'Rappel Facture N°1 – J-2'), ('facture1_overdue', 'Facture N°1 en retard'), ('facture2_ready', 'Facture N°2 à établir'), ('facture3_ready', 'Facture N°3 à établir'), ('d0_reminder', 'Rappel D0'), ('d6_reminder', 'Rappel D6')], max_length=30, verbose_name='Type')),
                ('priority', models.CharField(choices=[('critique', 'Critique'), ('important', 'Important'), ('normal', 'Normal')], default='normal', max_length=20, verbose_name='Priorité')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('unread', 'Non lue'), ('read', 'Lue'), ('processed', 'Traitée')], default='unread', max_length=20, verbose_name='Statut')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'envoi email")),
                ('email_error', models.TextField(blank=True, verbose_name='Erreur email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('project_engineers', 'Ingénieurs du projet'), ('billing_manager', 'Responsable facturation'), ('admin', 'Administrateur'), ('chef_projet', 'Chef de projet'), ('free_email', 'Adresse email libre')], max_length=30, verbose_name='Type de destinataire')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('channel', models.CharField(choices=[('app', 'Application'), ('email', 'Email'), ('both', 'Application + Email')], default='both', max_length=10, verbose_name='Canal')),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications_app.notification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'Destinataire',
                'verbose_name_plural': 'Destinataires',
            },
        ),
    ]
