# Generated by Django 6.0.4 on 2026-04-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
        ('projects', '0002_expertise_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.expertise', verbose_name='Expertise'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('facture1_ready', 'Facture N°1 à établir'), ('facture1_j7', 'Rappel Facture N°1 – J-7'), ('facture1_j2', 'Rappel Facture N°1 – J-2'), ('facture1_overdue', 'Facture N°1 en retard'), ('facture2_ready', 'Facture N°2 à établir'), ('facture3_ready', 'Facture N°3 à établir'), ('d0_reminder', 'Rappel D0'), ('d6_reminder', 'Rappel D6'), ('dao_str_alerte', 'DAO Structure – dossier en attente'), ('dao_elec_alerte', 'DAO Électricité – dossier en attente'), ('dao_fl_alerte', 'DAO Fluide – dossier en attente'), ('exe_str_alerte', 'EXE Structure – dossier en attente'), ('exe_elec_alerte', 'EXE Électricité – dossier en attente'), ('exe_fl_alerte', 'EXE Fluide – dossier en attente'), ('expertise_facture_ready', 'Expertise – Facture à établir'), ('expertise_facture_j10', 'Expertise – Rappel Facture J-10'), ('expertise_facture_j3', 'Expertise – Rappel Facture J-3'), ('expertise_facture_overdue', 'Expertise – Facture en retard')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notification_type',
            field=models.CharField(choices=[('facture1_ready', 'Facture N°1 à établir'), ('facture1_j7', 'Rappel Facture N°1 – J-7'), ('facture1_j2', 'Rappel Facture N°1 – J-2'), ('facture1_overdue', 'Facture N°1 en retard'), ('facture2_ready', 'Facture N°2 à établir'), ('facture3_ready', 'Facture N°3 à établir'), ('d0_reminder', 'Rappel D0'), ('d6_reminder', 'Rappel D6'), ('dao_str_alerte', 'DAO Structure – dossier en attente'), ('dao_elec_alerte', 'DAO Électricité – dossier en attente'), ('dao_fl_alerte', 'DAO Fluide – dossier en attente'), ('exe_str_alerte', 'EXE Structure – dossier en attente'), ('exe_elec_alerte', 'EXE Électricité – dossier en attente'), ('exe_fl_alerte', 'EXE Fluide – dossier en attente'), ('expertise_facture_ready', 'Expertise – Facture à établir'), ('expertise_facture_j10', 'Expertise – Rappel Facture J-10'), ('expertise_facture_j3', 'Expertise – Rappel Facture J-3'), ('expertise_facture_overdue', 'Expertise – Facture en retard')], max_length=30, unique=True, verbose_name='Type de notification'),
        ),
    ]
