# Generated by Django 6.0.4 on 2026-04-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_add_expertise_to_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.TextField(verbose_name='Destinataires')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Heure d'envoi")),
                ('success', models.BooleanField(default=False, verbose_name='Succès')),
                ('error', models.TextField(blank=True, verbose_name='Erreur')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications_app.notification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'Journal email',
                'verbose_name_plural': 'Journal emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
